// src/constants/absentMembers.ts

export const BILL_2206205_ABSENTEES = [
    { name: '강대식', region: '대구 동구군위군을', party: '국민의힘' },
    { name: '강명구', region: '경북 구미시을', party: '국민의힘' },
    { name: '강민국', region: '경남 진주시을', party: '국민의힘' },
    { name: '강선영', region: '비례대표', party: '국민의힘' },
    { name: '강승규', region: '충남 홍성군예산군', party: '국민의힘' },
    { name: '고동진', region: '서울 강남구병', party: '국민의힘' },
    { name: '곽규택', region: '부산 서구동구', party: '국민의힘' },
    { name: '구자근', region: '경북 구미시갑', party: '국민의힘' },
    { name: '권성동', region: '강원 강릉시', party: '국민의힘' },
    { name: '권영세', region: '서울 용산구', party: '국민의힘' },
    { name: '권영진', region: '대구 달서구병', party: '국민의힘' },
    { name: '김건', region: '비례대표', party: '국민의힘' },
    { name: '김기웅', region: '대구 중구남구', party: '국민의힘' },
    { name: '김기현', region: '울산 남구을', party: '국민의힘' },
    { name: '김대식', region: '부산 사상구', party: '국민의힘' },
    { name: '김도읍', region: '부산 강서구', party: '국민의힘' },
    { name: '김미애', region: '부산 해운대구을', party: '국민의힘' },
    { name: '김민전', region: '비례대표', party: '국민의힘' },
    { name: '김상훈', region: '대구 서구', party: '국민의힘' },
    { name: '김석기', region: '경북 경주시', party: '국민의힘' },
    { name: '김선교', region: '경기 여주시양평군', party: '국민의힘' },
    { name: '김성원', region: '경기 동두천시양주시연천구을', party: '국민의힘' },
    { name: '김소희', region: '비례대표', party: '국민의힘' },
    { name: '김승수', region: '대구 북구을', party: '국민의힘' },
    { name: '김용태', region: '경기 포천시가평군', party: '국민의힘' },
    { name: '김위상', region: '비례대표', party: '국민의힘' },
    { name: '김은혜', region: '경기 성남시분당구을', party: '국민의힘' },
    { name: '김장겸', region: '비례대표', party: '국민의힘' },
    { name: '김재섭', region: '서울 도봉구갑', party: '국민의힘' },
    { name: '김정재', region: '경북 포항시북구', party: '국민의힘' },
    { name: '김종양', region: '경남 창원시의창구', party: '국민의힘' },
    { name: '김태호', region: '경남 양산시을', party: '국민의힘' },
    { name: '김형동', region: '경북 안동시예천군', party: '국민의힘' },
    { name: '김희정', region: '부산 연제구', party: '국민의힘' },
    { name: '나경원', region: '서울 동작구을', party: '국민의힘' },
    { name: '박대출', region: '경남 진주시갑', party: '국민의힘' },
    { name: '박덕흠', region: '충북 보은군옥천군영동군괴산군', party: '국민의힘' },
    { name: '박상웅', region: '경남 밀양시의령군함안군창녕군', party: '국민의힘' },
    { name: '박성민', region: '울산 중구', party: '국민의힘' },
    { name: '박성훈', region: '부산 북구을', party: '국민의힘' },
    { name: '박수민', region: '서울 강남구을', party: '국민의힘' },
    { name: '박수영', region: '부산 남구', party: '국민의힘' },
    { name: '박정하', region: '강원 원주시갑', party: '국민의힘' },
    { name: '박정훈', region: '서울 송파구갑', party: '국민의힘' },
    { name: '박준태', region: '비례대표', party: '국민의힘' },
    { name: '박충권', region: '비례대표', party: '국민의힘' },
    { name: '박형수', region: '경북 의성군청송군영덕군울진군', party: '국민의힘' },
    { name: '배준영', region: '인천 중구강화군옹진군', party: '국민의힘' },
    { name: '배현진', region: '서울 송파구을', party: '국민의힘' },
    { name: '백종헌', region: '부산 금정구', party: '국민의힘' },
    { name: '서명옥', region: '서울 강남구갑', party: '국민의힘' },
    { name: '서범수', region: '울산 울주군', party: '국민의힘' },
    { name: '서일준', region: '경남 거제시', party: '국민의힘' },
    { name: '서지영', region: '부산 동래구', party: '국민의힘' },
    { name: '서천호', region: '경남 사천시남해군하동군', party: '국민의힘' },
    { name: '성일종', region: '충남 서산시태안군', party: '국민의힘' },
    { name: '송석준', region: '경기 이천시', party: '국민의힘' },
    { name: '송언석', region: '경북 김천시', party: '국민의힘' },
    { name: '신동욱', region: '서울 서초구을', party: '국민의힘' },
    { name: '신성범', region: '경남 산청군함양군거창군합천군', party: '국민의힘' },
    { name: '안상훈', region: '비례대표', party: '국민의힘' },
    { name: '엄태영', region: '충북 제천시단양군', party: '국민의힘' },
    { name: '우재준', region: '대구 북구갑', party: '국민의힘' },
    { name: '유상범', region: '강원 홍천군횡성군영월군평창군', party: '국민의힘' },
    { name: '유영하', region: '대구 달서구갑', party: '국민의힘' },
    { name: '유용원', region: '비례대표', party: '국민의힘' },
    { name: '윤상현', region: '인천 동구미추홀구을', party: '국민의힘' },
    { name: '윤영석', region: '경남 양산시갑', party: '국민의힘' },
    { name: '윤재옥', region: '대구 달서구을', party: '국민의힘' },
    { name: '윤한홍', region: '경남 창원시마산회원구', party: '국민의힘' },
    { name: '이달희', region: '비례대표', party: '국민의힘' },
    { name: '이만희', region: '경북 영천시청도군', party: '국민의힘' },
    { name: '이상휘', region: '경북 포항시남구울릉군', party: '국민의힘' },
    { name: '이성권', region: '부산 사하구갑', party: '국민의힘' },
    { name: '이양수', region: '강원 속초시인제군고성군양양군', party: '국민의힘' },
    { name: '이인선', region: '대구 수성구을', party: '국민의힘' },
    { name: '이종배', region: '충북 충주시', party: '국민의힘' },
    { name: '이종욱', region: '경남 창원시진해구', party: '국민의힘' },
    { name: '이철규', region: '강원 동해시태백시삼척시정선군', party: '국민의힘' },
    { name: '이헌승', region: '부산 부산진구을', party: '국민의힘' },
    { name: '인요한', region: '비례대표', party: '국민의힘' },
    { name: '임이자', region: '경북 상주시문경시', party: '국민의힘' },
    { name: '임종득', region: '경북 영주시영양군봉화군', party: '국민의힘' },
    { name: '장동혁', region: '충남 보령시서천군', party: '국민의힘' },
    { name: '정동만', region: '부산 기장군', party: '국민의힘' },
    { name: '정성국', region: '부산 부산진구갑', party: '국민의힘' },
    { name: '정연욱', region: '부산 수영구', party: '국민의힘' },
    { name: '정점식', region: '경남 통영시고성군', party: '국민의힘' },
    { name: '정희용', region: '경북 고령군성주군칠곡군', party: '국민의힘' },
    { name: '조경태', region: '부산 사하구을', party: '국민의힘' },
    { name: '조배숙', region: '비례대표', party: '국민의힘' },
    { name: '조승환', region: '부산 중구영도구', party: '국민의힘' },
    { name: '조은희', region: '서울 서초구갑', party: '국민의힘' },
    { name: '조정훈', region: '서울 마포구갑', party: '국민의힘' },
    { name: '조지연', region: '경북 경산시', party: '국민의힘' },
    { name: '주진우', region: '부산 해운대구갑', party: '국민의힘' },
    { name: '주호영', region: '대구 수성구갑', party: '국민의힘' },
    { name: '진종오', region: '비례대표', party: '국민의힘' },
    { name: '최보윤', region: '비례대표', party: '국민의힘' },
    { name: '최수진', region: '비례대표', party: '국민의힘' },
    { name: '최은석', region: '대구 동구군위군갑', party: '국민의힘' },
    { name: '최형두', region: '경남 창원시마산합포구', party: '국민의힘' },
    { name: '추경호', region: '대구 달성군', party: '국민의힘' },
    { name: '한기호', region: '강원 춘천시철원군화천군양구군을', party: '국민의힘' },
    { name: '한지아', region: '비례대표', party: '국민의힘' }
  ] as const;